version: 0.1

phases:
  pre_build:
    commands:
      - pip3 install awscli --upgrade --user
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain alphaomega-repo --domain-owner 127418365645 --region us-east-1 --query authorizationToken --output text`
      - cp ./settings.xml /root/.m2/settings.xml
  build:
    commands:
      - echo Build started on `date`
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - ./mvnw deploy
artifacts:
  files:
    - alpha-omega-core/target/alpha-omega-core-0.0.1-SNAPSHOT.jar