version: 0.2

phases:
#  install:
#    runtime-versions:
#      java: corretto11
#  pre_build:
#    commands:
#      - pip3 install awscli --upgrade --user
#      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain alphaomega-repo --domain-owner 127418365645 --region us-east-1 --query authorizationToken --output text`
#      - cp ./settings.xml /root/.m2/settings.xml
  build:
    commands:
      - echo deploying code on `date`
      - echo Build started on `date`
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain alphaomega-repo --domain-owner 127418365645 --region us-east-1 --query authorizationToken --output text`
      - echo '$CODEARTIFACT_AUTH_TOKEN'
      - mvn -s settings.xml clean deploy
artifacts:
  files:
    - alpha-omega-core/target/alpha-omega-core-0.0.1-SNAPSHOT.jar