name: maven
on:
  push

jobs:

  maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install with Maven
        run: ./mvnw clean install
  maven-to-code-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - uses: alphaomegaintegration/alpha-omega-parent/.github/workflows/maven-to-code-artifact.yml
        with:
          domain-owner: ${{env.AWS_REPO_DOMAIN_OWNER}}
          domain: ${{env.AWS_REPO_DOMAIN}}
          region: ${{env.AWS_REGION}}
        secrets: inherit
